---
title: "Processing the T Cells dataset for using with `iSEE`"
author:
- name: Federico Marini^[marinif@uni-mainz.de]
  affiliation: Institute of Medical Biostatistics, Epidemiology and Informatics ([IMBEI, Mainz](https://www.unimedizin-mainz.de/imbei/imbei/welcome-page.html?L=1))
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
    theme: lumen
---

# From Python (AnnData) to Loom

```{r}
library("reticulate")
# reticulate::py_install(c("scanpy", "python-igraph", "louvain", "loompy"))
```


```{python, eval=FALSE}
import scanpy as sc
ad_processed=sc.read_h5ad("T0_T1_Tcells_global_tcrdata.h5ad")
ad_processed.write_csvs("T0_T1_Tcells_global_tcrdata")
ad_processed.write_loom("T0_T1_Tcells_global_tcrdata/processed.loom")
```

# From Loom to SingleCellExperiment

```{r}
library("SingleCellExperiment")
counts_raw <- HDF5Array::HDF5Array(filepath = "T0_T1_Tcells_global_tcrdata/processed.loom", name = "matrix")
sce <- SingleCellExperiment(
  list(
    counts = t(counts_raw), 
    logcounts= t(counts_raw)
  )
)
sce
reducedDims(sce) <- list(
  PCA = rio::import("T0_T1_Tcells_global_tcrdata/obsm.csv")[,1:50], 
  UMAP = rio::import("T0_T1_Tcells_global_tcrdata/obsm.csv")[51:52]
)
sce

# rio::import("T0_T1_Tcells_global_tcrdata/obs.csv")
# rio::import("T0_T1_Tcells_global_tcrdata/var.csv")

rowdata_df <- rio::import("T0_T1_Tcells_global_tcrdata/var.csv")
DataFrame(rowdata_df)
rownames(sce)
rownames(sce) <- rowdata_df$index
sce

colData(sce) <- DataFrame(rio::import("T0_T1_Tcells_global_tcrdata/obs.csv"))
colnames(sce) <- paste0("cell_", seq_len(nrow(colData(sce))))
sce
```



```{r}
# saveRDS(sce, "sce_monocytes.RDS")
# sce <- readRDS("sce_monocytes.RDS")
### saveRDS(sce, "sce_Bcells.RDS")
# HDF5Array::saveHDF5SummarizedExperiment(sce, dir = "see_Tcells")

# sce <- readRDS("sce_Tcells.RDS")
sce <- HDF5Array::loadHDF5SummarizedExperiment("see_Tcells/")
```

Remaking Fig 5b


```{r}
scater::plotUMAP(sce, colour_by="manual_annotation")
```


# Setting up the iSEE instance

```{r eval=FALSE}
library("iSEE")
iSEE(sce)
library("iSEEu")
modeEmpty(sce)

# exported configuration of panels
initial <- list()

################################################################################
# Settings for Reduced dimension plot 1
################################################################################

initial[["ReducedDimensionPlot1"]] <- new("ReducedDimensionPlot", Type = "UMAP", XAxis = 1L, YAxis = 2L, 
    ColorByColumnData = "severity_time", ColorByFeatureNameAssay = "logcounts", 
    ColorBySampleNameColor = "#FF0000", ShapeByColumnData = "index", 
    SizeByColumnData = "n_genes", FacetByRow = "---", FacetByColumn = "---", 
    ColorBy = "Column data", ColorByDefaultColor = "#000000", 
    ColorByFeatureName = "AL669831.5", ColorByFeatureSource = "---", 
    ColorByFeatureDynamicSource = FALSE, ColorBySampleName = "cell_1", 
    ColorBySampleSource = "---", ColorBySampleDynamicSource = FALSE, 
    ShapeBy = "None", SizeBy = "None", SelectionEffect = "Transparent", 
    SelectionColor = "#FF0000", SelectionAlpha = 0.1, ZoomData = numeric(0), 
    BrushData = list(), VisualBoxOpen = TRUE, VisualChoices = "Color", 
    ContourAdd = FALSE, ContourColor = "#0000FF", PointSize = 1, 
    PointAlpha = 1, Downsample = FALSE, DownsampleResolution = 200, 
    CustomLabels = FALSE, CustomLabelsText = "cell_1", FontSize = 1, 
    LegendPointSize = 1, LegendPosition = "Bottom", HoverInfo = TRUE, 
    LabelCenters = FALSE, LabelCentersBy = "index", LabelCentersColor = "#000000", 
    PanelId = 1L, PanelHeight = 500L, PanelWidth = 3L, SelectionBoxOpen = FALSE, 
    RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, RowSelectionType = "Active", 
    RowSelectionSaved = 0L, ColumnSelectionDynamicSource = FALSE, 
    ColumnSelectionType = "Active", ColumnSelectionSaved = 0L, 
    SelectionHistory = list())

################################################################################
# Settings for Reduced dimension plot 2
################################################################################

initial[["ReducedDimensionPlot2"]] <- new("ReducedDimensionPlot", Type = "UMAP", XAxis = 1L, YAxis = 2L, 
    ColorByColumnData = "manual_annotation", ColorByFeatureNameAssay = "logcounts", 
    ColorBySampleNameColor = "#FF0000", ShapeByColumnData = "index", 
    SizeByColumnData = "n_genes", FacetByRow = "---", FacetByColumn = "---", 
    ColorBy = "Column data", ColorByDefaultColor = "#000000", 
    ColorByFeatureName = "AL669831.5", ColorByFeatureSource = "---", 
    ColorByFeatureDynamicSource = FALSE, ColorBySampleName = "cell_1", 
    ColorBySampleSource = "---", ColorBySampleDynamicSource = FALSE, 
    ShapeBy = "None", SizeBy = "None", SelectionEffect = "Transparent", 
    SelectionColor = "#FF0000", SelectionAlpha = 0.1, ZoomData = numeric(0), 
    BrushData = list(), VisualBoxOpen = TRUE, VisualChoices = "Color", 
    ContourAdd = FALSE, ContourColor = "#0000FF", PointSize = 1, 
    PointAlpha = 1, Downsample = FALSE, DownsampleResolution = 200, 
    CustomLabels = FALSE, CustomLabelsText = "cell_1", FontSize = 1, 
    LegendPointSize = 1, LegendPosition = "Bottom", HoverInfo = TRUE, 
    LabelCenters = FALSE, LabelCentersBy = "index", LabelCentersColor = "#000000", 
    PanelId = 2L, PanelHeight = 500L, PanelWidth = 3L, SelectionBoxOpen = FALSE, 
    RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, RowSelectionType = "Active", 
    RowSelectionSaved = 0L, ColumnSelectionDynamicSource = FALSE, 
    ColumnSelectionType = "Active", ColumnSelectionSaved = 0L, 
    SelectionHistory = list())

################################################################################
# Settings for Reduced dimension plot 3
################################################################################

initial[["ReducedDimensionPlot3"]] <- new("ReducedDimensionPlot", Type = "UMAP", XAxis = 1L, YAxis = 2L, 
    ColorByColumnData = "index", ColorByFeatureNameAssay = "logcounts", 
    ColorBySampleNameColor = "#FF0000", ShapeByColumnData = "index", 
    SizeByColumnData = "n_genes", FacetByRow = "---", FacetByColumn = "---", 
    ColorBy = "Feature name", ColorByDefaultColor = "#000000", 
    ColorByFeatureName = "IFI44L", ColorByFeatureSource = "RowDataTable1", 
    ColorByFeatureDynamicSource = FALSE, ColorBySampleName = "cell_1", 
    ColorBySampleSource = "---", ColorBySampleDynamicSource = FALSE, 
    ShapeBy = "None", SizeBy = "None", SelectionEffect = "Transparent", 
    SelectionColor = "#FF0000", SelectionAlpha = 0.1, ZoomData = numeric(0), 
    BrushData = list(), VisualBoxOpen = TRUE, VisualChoices = "Size", 
    ContourAdd = FALSE, ContourColor = "#0000FF", PointSize = 0.3, 
    PointAlpha = 1, Downsample = FALSE, DownsampleResolution = 200, 
    CustomLabels = FALSE, CustomLabelsText = "cell_1", FontSize = 1, 
    LegendPointSize = 1, LegendPosition = "Bottom", HoverInfo = TRUE, 
    LabelCenters = FALSE, LabelCentersBy = "index", LabelCentersColor = "#000000", 
    PanelId = 3L, PanelHeight = 500L, PanelWidth = 3L, SelectionBoxOpen = FALSE, 
    RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, RowSelectionType = "Active", 
    RowSelectionSaved = 0L, ColumnSelectionDynamicSource = FALSE, 
    ColumnSelectionType = "Active", ColumnSelectionSaved = 0L, 
    SelectionHistory = list())

################################################################################
# Settings for Row data table 1
################################################################################

initial[["RowDataTable1"]] <- new("RowDataTable", Selected = "IFI44L", Search = "IFI", SearchColumns = "", 
    HiddenColumns = character(0), PanelId = 1L, PanelHeight = 500L, 
    PanelWidth = 3L, SelectionBoxOpen = FALSE, RowSelectionSource = "---", 
    ColumnSelectionSource = "---", DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, 
    RowSelectionType = "Active", RowSelectionSaved = 0L, ColumnSelectionDynamicSource = FALSE, 
    ColumnSelectionType = "Active", ColumnSelectionSaved = 0L, 
    SelectionHistory = list())

################################################################################
# Settings for Feature assay plot 1
################################################################################

initial[["FeatureAssayPlot1"]] <- new("FeatureAssayPlot", Assay = "logcounts", XAxis = "Column data", 
    XAxisColumnData = "severity_time", XAxisFeatureName = "AL669831.5", 
    XAxisFeatureSource = "---", XAxisFeatureDynamicSource = FALSE, 
    YAxisFeatureName = "IFI44L", YAxisFeatureSource = "---", 
    YAxisFeatureDynamicSource = FALSE, ColorByColumnData = "index", 
    ColorByFeatureNameAssay = "logcounts", ColorBySampleNameColor = "#FF0000", 
    ShapeByColumnData = "index", SizeByColumnData = "n_genes", 
    FacetByRow = "---", FacetByColumn = "---", ColorBy = "None", 
    ColorByDefaultColor = "#000000", ColorByFeatureName = "AL669831.5", 
    ColorByFeatureSource = "---", ColorByFeatureDynamicSource = FALSE, 
    ColorBySampleName = "cell_1", ColorBySampleSource = "---", 
    ColorBySampleDynamicSource = FALSE, ShapeBy = "None", SizeBy = "None", 
    SelectionEffect = "Transparent", SelectionColor = "#FF0000", 
    SelectionAlpha = 0.1, ZoomData = numeric(0), BrushData = list(), 
    VisualBoxOpen = FALSE, VisualChoices = c("Color", "Facet"
    ), ContourAdd = FALSE, ContourColor = "#0000FF", PointSize = 1, 
    PointAlpha = 1, Downsample = FALSE, DownsampleResolution = 200, 
    CustomLabels = FALSE, CustomLabelsText = "cell_1", FontSize = 1, 
    LegendPointSize = 1, LegendPosition = "Bottom", HoverInfo = TRUE, 
    LabelCenters = FALSE, LabelCentersBy = "index", LabelCentersColor = "#000000", 
    PanelId = 1L, PanelHeight = 500L, PanelWidth = 4L, SelectionBoxOpen = FALSE, 
    RowSelectionSource = "---", ColumnSelectionSource = "---", 
    DataBoxOpen = FALSE, RowSelectionDynamicSource = FALSE, RowSelectionType = "Active", 
    RowSelectionSaved = 0L, ColumnSelectionDynamicSource = FALSE, 
    ColumnSelectionType = "Active", ColumnSelectionSaved = 0L, 
    SelectionHistory = list())

################################################################################
# Settings for Complex heatmap 1
################################################################################

initial[["ComplexHeatmapPlot1"]] <- new("ComplexHeatmapPlot", Assay = "logcounts", CustomRows = TRUE, 
    CustomRowsText = "IFI44L\nXAF1\nMX1\nMX2\nIFI6\nIRF7\nIFIT3", 
    ClusterRows = TRUE, ClusterRowsDistance = "spearman", ClusterRowsMethod = "ward.D2", 
    DataBoxOpen = FALSE, VisualChoices = "Annotations", ColumnData = character(0), 
    RowData = character(0), CustomBounds = FALSE, LowerBound = NA_real_, 
    UpperBound = NA_real_, AssayCenterRows = FALSE, AssayScaleRows = FALSE, 
    DivergentColormap = "purple < black < yellow", ShowDimNames = "Rows", 
    LegendPosition = "Bottom", LegendDirection = "Horizontal", 
    VisualBoxOpen = FALSE, SelectionEffect = "Color", SelectionColor = "#FF0000", 
    PanelId = 1L, PanelHeight = 500L, PanelWidth = 5L, SelectionBoxOpen = FALSE, 
    RowSelectionSource = "---", ColumnSelectionSource = "---", 
    RowSelectionDynamicSource = FALSE, RowSelectionType = "Active", 
    RowSelectionSaved = 0L, ColumnSelectionDynamicSource = FALSE, 
    ColumnSelectionType = "Active", ColumnSelectionSaved = 0L, 
    SelectionHistory = list())
# exported code for the plots
```


```{r eval=FALSE}
iSEE(sce, initial = initial)
```


# Session info {-}

```{r}
sessionInfo()
```



